### ISSUE TITLE
Does not work with Shifting Wares Mod

### ISSUE THREAD

**Issue by lumagatto** [DrexHD/VillagerConfig#38]
Vanilla trades reappear after a trade reset

**Comment by DrexHD** [comment]
This seems like a pretty annoying to solve mod incompatibility...! I don't have any idea or the time to fix this at the moment ):

**Comment by Estecka** [comment]
Hi, I think I can come up with an interface that would make compatibility easier. There's a just couple of things I'd like to confirm about how VC does thing:
- Do your trade pools still use Mojang's trade offer factories ? (I think they're called `VillagerTrades.ItemListing` in mojmap?)
- If I understand "groups" correctly, they're basically just sub-tiers withing tiers, right ? If so that means I can flatten things out on my side, and treat each group as if it were its own vanilla tier.

**Comment by DrexHD** [comment]
> Do your trade pools still use Mojang's trade offer factories ? (I think they're called `VillagerTrades.ItemListing` in mojmap?)

Yes `VillagerTrades$ItemListing` is the mojmap of `TradeOffers$Factory`. `BehaviorTrade`, the main class used in VC, implements this for easier / better vanilla compatibility.

> If I understand "groups" correctly, they're basically just sub-tiers withing tiers, right ? If so that means I can flatten things out on my side, and treat each group as if it were its own vanilla tier.

If Villagerconfig is present, something like this should work to get all Trade Offers for a specific tier (1 indexed):
*(mojmap)*
```java
public static VillagerTrades.ItemListing[] getTrades(Villager villager, int tier) {
    TradeTable tradeTable = VillagerConfig.TRADE_MANAGER.getTrade(BuiltInRegistries.VILLAGER_PROFESSION.getKey(villager.getVillagerData().getProfession()));
    if (tradeTable != null) {
        return tradeTable.getTradeOffers(villager, tier);
    } else {
        // Vanilla code
    }
}
```

**Comment by DrexHD** [comment]
Yeah, sorry. It returns _one_ possible choice (of trades) for that tier. I assumed that wouldn't really matter to you, since you only pick a random one regardless, but I guess you want to have some "not the same again" logic (?).

**Comment by Estecka** [comment]
I don't think duplicate trades are going to be an issue anyways. What I try to do is distribute the trades in a pattern that is as close as possible to what it would look like by simply by leveling up a villager. 

Having a pre-selection might work a little better, but if I treat it like a pool, the trades from different groups would still end up being mixed together. Trades from one group could end up being rerolled into trades from a different group.

With direct access to groups themselves, the code would look a little more like this:
```java
```

**Comment by DrexHD** [comment]
> Having a pre-selection might work a little better, but either way, if I treat it like a pool, the trades from different groups would still end up being mixed together. Trades from one group could end up being rerolled into trades from a different group.

I am not sure this can be avoided. How do you even want to properly detect which group the previous trades was in?

> While writing this I also realized groups' `numToSelect` isn't actually an int, but a `NumberProvider`. Does this means two villagers of the same profession and the same level could have a different amount of trade offers ?

Yes that could happen, if `numToSelect` is not a constant.

**Comment by Estecka** [comment]
> How do you even want to properly detect which group the previous trades was in?
I just ask the group how large it is, and assign the group to as many slots.
If this wasn't clear, the return value of `GetTradeLayout` associates a pool with each individual slot.

**Comment by Estecka** [comment]
On a completely separate matter. I had a system that prevents villager from endlessly generating and throwing away new maps, and instead preserve the one they originally sell. With vanilla I did that by [mixing into the TreasureMapForEmeralds](https://github.com/Estecka/mc-Shifting-Wares/blob/1.20.1/src/main/java/tk/estecka/shiftingwares/mixin/SellMapFactoryMixin.java), but you seem to convert all vanilla factories into BehaviourTrades. How do you think I could do something similar here ?

**Comment by DrexHD** [comment]
> I just ask the group how large it is, and assign the group to as many slots.
If this wasn't clear, the return value of `GetTradeLayout` associates a pool with each individual slot.

mmh, "asking the group how large it is" won't work "100% reliably" with vc, because as you mentioned `numToSelect` is not guaranteed to be constant.

> On a completely separate matter. I had a system that prevents villager from endlessly generating and throwing away new maps, and instead preserve the one they originally sell. With vanilla I did that by [mixing into the TreasureMapForEmeralds](https://github.com/Estecka/mc-Shifting-Wares/blob/1.20.1/src/main/java/tk/estecka/shiftingwares/mixin/SellMapFactoryMixin.java), but you seem to convert all vanilla factories into BehaviourTrades. How do you think I could do something similar here ?

I am converting all trades to `BehaviourTrade`, which use vanillas item loot pools internally. Map trades are converted to `ExplorationMapFunction` (mojmap) / `ExplorationMapLootFunction` (yarn), which is an [item modifier](https://minecraft.wiki/w/Item_modifier) `exploration_map`. It's probably possible to have a similar mixin in `ExplorationMapFunction.run(ItemStack itemStack, LootContext lootContext)`, which checks the loot context for an entity [(vc provides the villager entity as `THIS_ENTITY`)](https://github.com/DrexHD/VillagerConfig/blob/1.20/stable/src/main/java/me/drex/villagerconfig/data/BehaviorTrade.java#L80)

**Comment by Estecka** [comment]
> mmh, "asking the group how large it is" won't work "100% reliably" with vc, because as you mentioned `numToSelect` is not guaranteed to be constant.

At first I was worried about this too, but in the end I think it's not a problem that the amount of trades can vary. Yes, it makes it possible for a slot to change group, but that also means this slot could have belonged to either group to begin with. In which case I won't consider the change to be a mistake; it's a reroll working as intended. 

Regardless of whether I do anything about groups, tiers will also behave in the same way; their sizes will vary from one reroll to another, so some slots will end up changing tier, depending on how generous the villager is feeling today.

**Comment by DrexHD** [comment]
VillagerConfig used to have jitpack releases, because I wanted to allow other mods to add (de)serialization for their custom trade factories, but this is no longer useful. It's no longer really intended to be depended upon, so modrinth maven is your best bet. 
I think a lot of the changes in V4.1 were due to the experimental villager trade changes. What exactly has changed that you rely on?

**Comment by Estecka** [comment]
In particular, the classes `TradeTable`, `TradeTier` and `TradeGroup` were moved from the package `me.drex.villagerconfig.json.data` to `me.drex.villagerconfig.data`, (making them completely different classes from the code's viewpoint). Their methods "GetTrades" and "GetTradeOffers" was changed from taking a `RandomSource` as parameter, to taking an `AbtractVillager`.

(While calling `TradeTable::getTradeOffers` for each tier yields acceptable results, I still find that being able to [access the trade groups individually](https://github.com/Estecka/mc-ShiftingWares-VillagerConfig-addon/blob/d9e5e4cf0fc0a929d3bb16f459460aecc72abffc/src/main/java/tk/estecka/shiftingwares/villagerconfig/VillagerConfigTradeLayout.java) gives better results.)

It's not that I don't know how to handle these changes, but if possible I'd like to avoid having to mainting different code bases for each version of VC. For the purpose of long-term compatibility, making those functions accessible from a dedicated API, so that VC can be safely depended upon, would actually be the best option.

**Comment by DrexHD** [comment]
Wow this was more work than expected (1.20.2 really changed a lot of the serialization code, and some other stuff). I have just released `v4.1.2+1.20.1`, which should have the same methods (you need) on both version.

**Comment by Estecka** [comment]
Compatibility addon released [here](https://modrinth.com/mod/shiftingwares-villagerconfig-addon)

**Comment by DrexHD** [comment]
Nice work, thanks a lot!
